#!/usr/bin/env python
"""Convert a Polymetis_Franka_Teleop session into a GR00T LeRobot v2.1 dataset
targeting the ``OXE_DROID_RELATIVE_EEF_RELATIVE_JOINT`` embodiment.

Phase 2-1 final spec (cmd-based DROID action convention; per-episode parquet;
custom dual-exterior video keys with positional auto-map to GR00T's
``exterior_image_1_left`` / ``wrist_image_left`` modality slots).

Layout produced
---------------
<output>/
  data/chunk-000/episode_NNNNNN.parquet
  videos/chunk-000/observation.images.exterior_1_left/episode_NNNNNN.mp4   # symlink to session cam0
  videos/chunk-000/observation.images.exterior_2_left/episode_NNNNNN.mp4   # symlink to session cam1
  meta/
    info.json          LeRobot v2.1 dataset descriptor
    episodes.jsonl     per-episode length + task description
    tasks.jsonl        unique task instruction list
    modality.json      GR00T field-split spec (eef_9d / gripper / joint, 2 video keys)
    stats.json         generated by ``gr00t.data.stats`` (mean/std/min/max/q01/q99 + relative_stats)

State / Action layout (17D each, must match modality.json)
----------------------------------------------------------
  [0:9]    eef_9d            position(3) + rot6d_continuous(6) from quaternion
  [9:10]   gripper_position  normalized to [0, 1] via max_width_m
  [10:17]  joint_position    Franka 7DOF in radians

Action is the operator-commanded target (DROID convention), NOT next-step
state.  ``robot0_*`` keys feed state; ``action_*_cmd`` keys feed action.
``action.gripper_position`` is the only exception: our pipeline does not
store a gripper command stream at the action grid, so we fall back to
``robot0_gripper_width[t+1]`` (a 1-frame state lookahead) with last-frame
clamp.  See Batch 2 Phase 2-1 final spec for the full rationale.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import zarr

from polymetis_franka_teleop.common.rotation_util import quat_to_rot6d

# ``_conversion_common`` lives next to this script; Python adds the
# script's directory to sys.path[0] when invoked as
# ``python scripts_real/<file>.py``, so a same-dir import works without
# making ``scripts_real`` a package.
from _conversion_common import (  # noqa: E402  (sibling-script import)
    classify_cams,
    load_session,
)


# ============================== Constants ==============================

# State / action share the same 17D layout.  Indices match the modality.json
# we emit below; if you change one, change the other.
STATE_DIM = ACTION_DIM = 17

# Video keys we write into ``modality.json``.  GR00T's pretrained
# ``oxe_droid_relative_eef_relative_joint`` embodiment expects exactly
# these two keys (see ``gr00t.configs.data.embodiment_configs.MODALITY_CONFIGS``).
# Matching the names here makes ``LeRobotEpisodeLoader`` use name-based
# mapping and skip the positional fallback warning at
# ``lerobot_episode_loader.py:276-295``.
LOGICAL_VIDEO_KEYS = ("exterior_image_1_left", "wrist_image_left")
ORIGINAL_VIDEO_KEYS = tuple(f"observation.images.{k}" for k in LOGICAL_VIDEO_KEYS)

# Placeholder task description for sandbox sessions whose language.json
# carries ``instruction: null``.  Enabled only with --allow-placeholder.
PLACEHOLDER_TASK = "perform manipulation task"


# ============================== Per-episode state/action ==============================


def compute_state_action(
    root: zarr.Group,
    max_width: float,
    ep_start: int,
    ep_end: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Slice one episode and assemble its (N, 17) state + action arrays.

    state[t]:
      [0:3]   robot0_eef_pos[t]                                       (TCP frame, m)
      [3:9]   rot6d(robot0_eef_orientation_quat[t])                   (Zhou et al. 6D)
      [9]     robot0_gripper_width[t] / max_width                     (normalized)
      [10:17] robot0_joint_pos[t]                                     (rad)

    action[t]:
      [0:3]   action_ee_position_cmd[t]                               (operator cmd)
      [3:9]   rot6d(action_ee_orientation_quat_cmd[t])
      [9]     robot0_gripper_width[min(t+1, N-1)] / max_width         (next-step state proxy)
      [10:17] action_joint_position_cmd[t]
    """
    s = slice(ep_start, ep_end)
    eef_pos   = np.asarray(root["data/robot0_eef_pos"][s],                  dtype=np.float64)
    eef_quat  = np.asarray(root["data/robot0_eef_orientation_quat"][s],     dtype=np.float64)
    joint_pos = np.asarray(root["data/robot0_joint_pos"][s],                dtype=np.float64)
    g_width   = np.asarray(root["data/robot0_gripper_width"][s],            dtype=np.float64).reshape(-1)
    cmd_pos   = np.asarray(root["data/action_ee_position_cmd"][s],          dtype=np.float64)
    cmd_quat  = np.asarray(root["data/action_ee_orientation_quat_cmd"][s],  dtype=np.float64)
    cmd_jpos  = np.asarray(root["data/action_joint_position_cmd"][s],       dtype=np.float64)

    n = eef_pos.shape[0]
    if n == 0:
        raise ValueError(f"empty episode slice [{ep_start}:{ep_end}]")

    rot6d_state  = quat_to_rot6d(eef_quat)
    rot6d_action = quat_to_rot6d(cmd_quat)

    # ---- state ----
    state = np.zeros((n, STATE_DIM), dtype=np.float32)
    state[:, 0:3]   = eef_pos
    state[:, 3:9]   = rot6d_state
    state[:, 9]     = g_width / max_width
    state[:, 10:17] = joint_pos

    # ---- action gripper: t+1 state with last-frame clamp ----
    g_next = g_width.copy()
    if n > 1:
        g_next[:-1] = g_width[1:]
    # g_next[-1] stays as g_width[-1] (fallback)

    action = np.zeros((n, ACTION_DIM), dtype=np.float32)
    action[:, 0:3]   = cmd_pos
    action[:, 3:9]   = rot6d_action
    action[:, 9]     = g_next / max_width
    action[:, 10:17] = cmd_jpos
    return state, action


# ============================== Parquet + videos ==============================


def write_parquet(
    state: np.ndarray,
    action: np.ndarray,
    fps: int,
    episode_index: int,
    task_index: int,
    global_index_start: int,
    out_path: Path,
) -> None:
    """Write minimal LeRobot v2.1 + GR00T parquet (7 columns)."""
    n = state.shape[0]
    timestamp = np.arange(n, dtype=np.float64) / float(fps)
    frame_index = np.arange(n, dtype=np.int64)
    episode_index_arr = np.full(n, episode_index, dtype=np.int64)
    index_arr = np.arange(global_index_start, global_index_start + n, dtype=np.int64)
    task_index_arr = np.full(n, task_index, dtype=np.int64)

    df = pd.DataFrame({
        "observation.state": list(state),
        "action":            list(action),
        "timestamp":         timestamp,
        "frame_index":       frame_index,
        "episode_index":     episode_index_arr,
        "index":             index_arr,
        "task_index":        task_index_arr,
    })
    table = pa.Table.from_pandas(df, preserve_index=False)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(table, out_path)


def symlink_videos(
    session_dir: Path,
    output_dir: Path,
    episode_index: int,
    cam_video_map: dict[int, str],
) -> None:
    """Symlink each cam mp4 into the LeRobot video tree under its DROID key.

    Symlinks rather than copies: zero space cost, fast, and the rmtree
    semantics of ``drop_episode`` are preserved (rmtree on the session's
    per-episode dir invalidates these symlinks as expected).

    ``cam_video_map`` is the per-session result of ``_classify_cams``:
    ``{cam_idx -> "observation.images.<wrist|exterior_image_1>_left"}``.
    """
    chunk_id = episode_index // 1000
    for cam_idx, original_key in cam_video_map.items():
        src = (session_dir / "videos" / str(episode_index) / f"{cam_idx}.mp4").resolve()
        if not src.exists():
            raise FileNotFoundError(f"missing mp4 for ep={episode_index} cam={cam_idx}: {src}")
        dst_dir = output_dir / "videos" / f"chunk-{chunk_id:03d}" / original_key
        dst_dir.mkdir(parents=True, exist_ok=True)
        dst = dst_dir / f"episode_{episode_index:06d}.mp4"
        if dst.is_symlink() or dst.exists():
            dst.unlink()
        os.symlink(src, dst)


# ============================== meta/ files ==============================


def _video_shape(session_dir: Path, episode_index: int, cam_idx: int) -> tuple[int, int]:
    """Read (height, width) from the session's per-cam intrinsics JSON."""
    p = session_dir / "videos" / str(episode_index) / "calibration" / f"cam_{cam_idx}.json"
    with open(p) as f:
        calib = json.load(f)
    intr = calib["intrinsics"]
    return int(intr["height"]), int(intr["width"])


def _video_shape_by_key(
    session_dir: Path,
    episode_index: int,
    cam_video_map: dict[int, str],
    original_key: str,
) -> tuple[int, int]:
    """Lookup (H, W) for a given video-key by reversing the cam_video_map."""
    for cam_idx, k in cam_video_map.items():
        if k == original_key:
            return _video_shape(session_dir, episode_index, cam_idx)
    raise KeyError(f"{original_key} not in cam_video_map={cam_video_map}")


def write_meta(
    output_dir: Path,
    session: dict,
    fps: int,
    episode_summaries: list[dict],
    task_list: list[str],
    cam_video_map: dict[int, str],
) -> None:
    meta_dir = output_dir / "meta"
    meta_dir.mkdir(parents=True, exist_ok=True)

    # Per-video-key shape lookup via cam_video_map.  ZED Mini and ZED 2i can
    # use different image sizes; in VGA mode they're both 672x376 today, but
    # this stays correct if the operator changes camera_resolution.  Lookup
    # by original_key, not cam_idx, so the order in info.json["features"]
    # tracks the canonical modality.json ordering (exterior first, wrist
    # second).
    h_ext, w_ext = _video_shape_by_key(
        session["session_dir"], 0, cam_video_map, ORIGINAL_VIDEO_KEYS[0])
    h_wri, w_wri = _video_shape_by_key(
        session["session_dir"], 0, cam_video_map, ORIGINAL_VIDEO_KEYS[1])

    n_eps = len(episode_summaries)
    total_frames = sum(s["length"] for s in episode_summaries)

    info = {
        "codebase_version": "v2.1",
        "robot_type": "droid",
        "total_episodes": n_eps,
        "total_frames": total_frames,
        "fps": fps,
        "data_path": "data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet",
        "video_path": "videos/chunk-{episode_chunk:03d}/{video_key}/episode_{episode_index:06d}.mp4",
        "chunks_size": 1000,
        "splits": {"train": f"0:{n_eps}"},
        "features": {
            ORIGINAL_VIDEO_KEYS[0]: {"dtype": "video", "shape": [h_ext, w_ext, 3]},
            ORIGINAL_VIDEO_KEYS[1]: {"dtype": "video", "shape": [h_wri, w_wri, 3]},
            "observation.state":   {"dtype": "float32", "shape": [STATE_DIM]},
            "action":              {"dtype": "float32", "shape": [ACTION_DIM]},
            "task_index":          {"dtype": "int64",   "shape": [1]},
        },
    }
    with open(meta_dir / "info.json", "w") as f:
        json.dump(info, f, indent=2)

    with open(meta_dir / "episodes.jsonl", "w") as f:
        for s in episode_summaries:
            f.write(json.dumps({
                "episode_index": s["episode_index"],
                "tasks":         [s["task"]],
                "length":        s["length"],
            }) + "\n")

    with open(meta_dir / "tasks.jsonl", "w") as f:
        for i, t in enumerate(task_list):
            f.write(json.dumps({"task_index": i, "task": t}) + "\n")

    modality = {
        "state": {
            "eef_9d":           {"start": 0,  "end": 9},
            "gripper_position": {"start": 9,  "end": 10},
            "joint_position":   {"start": 10, "end": 17},
        },
        "action": {
            "eef_9d":           {"start": 0,  "end": 9},
            "gripper_position": {"start": 9,  "end": 10},
            "joint_position":   {"start": 10, "end": 17},
        },
        "video": {
            LOGICAL_VIDEO_KEYS[0]: {"original_key": ORIGINAL_VIDEO_KEYS[0]},
            LOGICAL_VIDEO_KEYS[1]: {"original_key": ORIGINAL_VIDEO_KEYS[1]},
        },
        "annotation": {
            "language.language_instruction": {"original_key": "task_index"},
        },
    }
    with open(meta_dir / "modality.json", "w") as f:
        json.dump(modality, f, indent=2)


# ============================== Task / instruction resolution ==============================


def resolve_instruction(lang: dict, allow_placeholder: bool) -> str:
    inst = lang.get("instruction") if lang else None
    if inst is None or inst == "":
        if not allow_placeholder:
            raise SystemExit(
                "Episode instruction is null/empty. Pass --allow-placeholder "
                "for sandbox/smoke sessions, or supply a real instruction "
                "before re-running."
            )
        return PLACEHOLDER_TASK
    return inst


# ============================== Main ==============================


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--input-session",   required=True, type=Path,
                        help="Path to a Polymetis_Franka_Teleop session dir (contains "
                             "replay_buffer.zarr + dataset_meta.json + videos/<ep>/).")
    parser.add_argument("--output-dataset",  required=True, type=Path,
                        help="LeRobot v2.1 dataset output dir.")
    parser.add_argument("--embodiment-tag",  default="OXE_DROID_RELATIVE_EEF_RELATIVE_JOINT",
                        help="GR00T embodiment tag (default: %(default)s).")
    parser.add_argument("--allow-placeholder", action="store_true",
                        help="Accept null language.json instruction with a fallback task "
                             "string (sandbox/smoke sessions only).")
    parser.add_argument("--max-episodes", type=int, default=-1,
                        help="Convert only the first N episodes (debugging). -1 = all.")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    session_dir = args.input_session.resolve()
    output_dir  = args.output_dataset.resolve()

    session = load_session(session_dir)
    fps = int(session["ds_meta"]["main_loop_rate_hz"])

    n_eps = session["n_episodes"]
    if args.max_episodes > 0:
        n_eps = min(n_eps, args.max_episodes)
    if n_eps == 0:
        print("No episodes to convert.", file=sys.stderr)
        return 1

    # Resolve instructions + build unique task list (stable order).
    instructions = [
        resolve_instruction(session["languages"][ep], args.allow_placeholder)
        for ep in range(n_eps)
    ]
    task_list: list[str] = []
    task_index_map: dict[str, int] = {}
    for inst in instructions:
        if inst not in task_index_map:
            task_index_map[inst] = len(task_list)
            task_list.append(inst)

    output_dir.mkdir(parents=True, exist_ok=True)

    # Per-session cam classification: which cam_<i> is wrist (ZED Mini) and
    # which is exterior (ZED 2i).  Done once from episode-0 intrinsics --
    # the physical setup is constant across a session. ``role_naming="lerobot"``
    # produces ``observation.images.<role>`` keys for the LeRobot v2.1
    # video tree and info.json features block.
    cam_video_map = classify_cams(session_dir, episode_index=0, role_naming="lerobot")
    if args.verbose:
        print(f"  cam_video_map = {cam_video_map}", flush=True)

    episode_summaries: list[dict] = []
    global_index = 0
    for ep in range(n_eps):
        ep_start = 0 if ep == 0 else int(session["episode_ends"][ep - 1])
        ep_end   = int(session["episode_ends"][ep])
        ep_len   = ep_end - ep_start

        state, action = compute_state_action(
            session["root"], session["max_width"], ep_start, ep_end,
        )

        chunk_id = ep // 1000
        parquet_path = output_dir / "data" / f"chunk-{chunk_id:03d}" / f"episode_{ep:06d}.parquet"
        task_idx = task_index_map[instructions[ep]]
        write_parquet(state, action, fps, ep, task_idx, global_index, parquet_path)
        symlink_videos(session_dir, output_dir, ep, cam_video_map)

        episode_summaries.append({
            "episode_index": ep,
            "task":          instructions[ep],
            "length":        ep_len,
        })
        global_index += ep_len
        if args.verbose:
            print(f"  ep {ep}: len={ep_len}  task_index={task_idx}  task='{instructions[ep]}'",
                  flush=True)

    write_meta(output_dir, session, fps, episode_summaries, task_list, cam_video_map)

    # ---- stats.json ----
    # Try the official GR00T tool first; it also emits ``meta/relative_stats.json``
    # for embodiments whose action_configs include a RELATIVE representation
    # (``LeRobotEpisodeLoader`` picks that up automatically when present).
    # Fall back to an inline computation that matches the algorithm in
    # ``gr00t.data.stats.calculate_dataset_statistics`` byte-for-byte
    # (mean/std/min/max/q01/q99 over each float feature, ``np.vstack`` ->
    # axis=0 reductions, JSON-serialised lists).  Inline path is needed
    # on hosts where ``gr00t`` isn't installed in the conda env that
    # runs the converter (e.g. pro4000's polymetis env).
    print("[stats] generating meta/stats.json ...", flush=True)
    try:
        from gr00t.data.embodiment_tags import EmbodimentTag  # noqa: F401
        from gr00t.data import stats as gr00t_stats
        emb = EmbodimentTag.resolve(args.embodiment_tag)
        gr00t_stats.main(dataset_path=output_dir, embodiment_tag=emb)
        print("[stats] done (via gr00t.data.stats; relative_stats.json included)",
              flush=True)
    except ModuleNotFoundError as e:
        print(f"[stats] gr00t module not available ({e}); using inline fallback "
              f"(matches gr00t.data.stats algorithm; no relative_stats.json)",
              flush=True)
        _generate_stats_inline(output_dir)
        print("[stats] done (inline)", flush=True)

    print(f"\nConverted {n_eps} episode(s) -> {output_dir}")
    return 0


# ============================== Inline stats fallback ==============================


def _generate_stats_inline(dataset_path: Path) -> None:
    """Inline copy of ``gr00t.data.stats.calculate_dataset_statistics`` +
    ``generate_stats`` for hosts without the ``gr00t`` package.

    Matches the algorithm byte-for-byte (same numpy reductions, same
    JSON layout, same six fields per feature).  Does NOT generate
    ``relative_stats.json`` because that requires the embodiment's
    ``action_configs`` registry from ``gr00t.configs.data.embodiment_configs``.
    LeRobotEpisodeLoader handles a missing ``relative_stats.json`` gracefully.
    """
    with open(dataset_path / "meta" / "info.json") as f:
        info = json.load(f)
    features = info["features"]
    float_features = [k for k, v in features.items() if "float" in v["dtype"]]

    parquet_files = sorted((dataset_path / "data").glob("chunk-*/*.parquet"))
    if not parquet_files:
        raise RuntimeError(f"no parquet files under {dataset_path / 'data'}")
    dfs = [pd.read_parquet(p) for p in parquet_files]
    df_all = pd.concat(dfs, axis=0)

    stats: dict[str, dict] = {}
    for feat in float_features:
        np_data = np.vstack(
            [np.asarray(x, dtype=np.float32) for x in df_all[feat]]
        )
        stats[feat] = {
            "mean": np.mean(np_data, axis=0).tolist(),
            "std":  np.std(np_data, axis=0).tolist(),
            "min":  np.min(np_data, axis=0).tolist(),
            "max":  np.max(np_data, axis=0).tolist(),
            "q01":  np.quantile(np_data, 0.01, axis=0).tolist(),
            "q99":  np.quantile(np_data, 0.99, axis=0).tolist(),
        }
    with open(dataset_path / "meta" / "stats.json", "w") as f:
        json.dump(stats, f, indent=4)


if __name__ == "__main__":
    raise SystemExit(main())
